### ISSUE TITLE
22-name raise

### ISSUE THREAD

**Issue by yuktikhurana** [osifoanosike/basicruby#12]
1. Not working. Getting exception. bad_request file is missing

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
1.Rescue the exception
2. No need to write such descriptive lines for the user
3. The exercise states the class to have to have two attributes firstname and lastname.

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
1. displaying name  should not be in initialize. create a method like show or override to_s for displaying name.

**Comment by osifoanosike** [comment]
to_s method created to handle display. Fixed

**Comment by yuktikhurana** [comment]
Why have you done name.to_s in main.rb?
Can you tell me what is the purpose of overriding to_s ? And what does puts do? 
Please answer in a comment. Also don't forget to assign back the issue to me after completing the fixes.

**Comment by osifoanosike** [comment]
1. Sorry, I was wrong. It was a redundant repetition, as puts already outputs name as a string.
2. puts returns the string representation (to_s) of the argument passed to it.

**Comment by yuktikhurana** [comment]
Very good. We just need to test that you know the purpose of writing any piece of code. And no need to be sorry. You're on the path of learning and we're here to correct and guide you.
Please make the neccessary changes and close this issue.

**Comment by osifoanosike** [comment]
ok. thanks
