### ISSUE TITLE
5. Customer Account Balance

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#16]

**Comment by abhishekjain16** [comment]
1. What if I enter any random character which is not Integer?
2. Question requires to define method with name deposit and withdraw and use them.

**Comment by abhishekjain16** [comment]
1. Also, there is issue with generating/assigning account number. Exercise was to have account number auto-incremented not passing account no.

**Comment by osifoanosike** [comment]
Fixed

**Comment by abhishekjain16** [comment]
No changes visible

**Comment by osifoanosike** [comment]
Sorry, i pushed all the changes after individually adding the "fixed" comments

**Comment by osifoanosike** [comment]
Please, you can now re-check

**Comment by osifoanosike** [comment]
Kindle re-check. Thanks

On Tue, Jan 6, 2015 at 9:57 AM, Abhishek Jain notifications@github.com
wrote:

> No changes visible
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osifoanosike/basicruby/issues/16#issuecomment-68840831
> .

## 

_Anosike Osifo_
Software Developer

DealDey Limited
m: +234 803 438 1098
www.dealdey.com http://www.dealdey.com/blog/
