### ISSUE TITLE
7. Inverse Case

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#18]

**Comment by abhishekjain16** [comment]
Check usage of swapcase! and swapcase.
This changes the original string

**Comment by osifoanosike** [comment]
Bang operator removed.

**Comment by Shruti2791** [comment]
1) Why do we have to initialize in the main class ?
2) Why do we need to assign the result in a variable ?
The last line of any function is automatically returned.

**Comment by osifoanosike** [comment]
Removed initialize, created the string instance implicitly
removed unnecessary assignments.
Fixed

**Comment by abhishekjain16** [comment]
Closing this, but please do not use unnecessary variables like  altered in to_s As in ruby method returns last line.

**Comment by osifoanosike** [comment]
Ok. I've removed the redundant assignment.
