### ISSUE TITLE
Ex-11 - Pascal triangle

### ISSUE THREAD

**Issue by Shruti2791** [osifoanosike/basicruby#3]
1) Function name 'execute' is inappropriate.
2) What will happen if the row count is zero or less than zero ? What do row count zero convey ? I think all these should be restricted entries. 
3) We do not have to return the last statement in a function. It gets automatically returned.(Line no. 5)
4) The output should print like a triangle.
5) The 'pascal' class is doing pretty lot of work. Keep only appropriate methods inside it. For instance factorial should not be a part of this class.

**Comment by osifoanosike** [comment]
Fixed
