### ISSUE TITLE
11. Pascal - Yield

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#32]

**Comment by Shruti2791** [comment]
Exercise is not functional .Returning NoMethodError: undefined method `factorial' for 0:Fixnum

**Comment by osifoanosike** [comment]
Fixed.
I forgot to update the path to the referenced fixnum.rb. Its working fine now. The factorial method is called from the referenced file.

**Comment by Shruti2791** [comment]
Correct the fixnum.rb class first as commented in its respective issue.

**Comment by osifoanosike** [comment]
In the referenced Fixnum class issue, Is it possible to check a 
Fixnum instance for string values?

**Comment by osifoanosike** [comment]
Fixed

**Comment by Shruti2791** [comment]
1) incorrect output
2) output should be in the form of a triangle

**Comment by osifoanosike** [comment]
Logic corrected
Output now in triangle form

**Comment by Shruti2791** [comment]
1) Why are we appending a string using interpolation when we can use an array here instead ? (line no 7 in pascal.rb)
2) Use yeild.

**Comment by osifoanosike** [comment]
Issue fixed.

**Comment by Shruti2791** [comment]
1) why main.rb have a puts in the last line ?
2) Why are we using 'while' in #draw_triangle  and not 'for' ?
3) Curly braces should have a space on either side inside them. (Please refer to https://github.com/styleguide/ruby )

**Comment by osifoanosike** [comment]
I was using puts to move the carriage return to the next line, I've corrected it
I  just choose to, no particular reasons.
Spacing corrected.

**Comment by osifoanosike** [comment]
loop structure corrected.
Spacing also corrected

**Comment by Shruti2791** [comment]
Looks good now 
My intent to draw your attention towards while loop was to tell you that with while you were creating an extra variable which was being intialized and then was being incremented. However this is automatically handled by 'for' loop.
