### ISSUE TITLE
9. Array - Hash

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#34]

**Comment by Shruti2791** [comment]
1)Pretty complex logic to assign arrays in hashes. There is a better way to the same. Refer hash class.

**Comment by osifoanosike** [comment]
Fixed.
Initialized array with block for simplification
Changed code logic.

**Comment by abhishekjain16** [comment]
Why are returning hash with inspect?
Closing it but do answer this.

**Comment by osifoanosike** [comment]
Inspect returns the content of the hash as a string. I removed it though, as i really don't need it.

**Comment by Shruti2791** [comment]
Try this exercise by directly calling create_hash method on an array. In this case taking input from the user is limiting us to check many other conditions which would have been checked otherwise as every entry here is converted into a string.

**Comment by osifoanosike** [comment]
Okay, i get it. I've made the corrections by checking for integer input. The code looks bulky though.
