### ISSUE TITLE
14. Reverse sentence

### ISSUE THREAD

**Issue by Shruti2791** [osifoanosike/basicruby#36]
1) Why do we need 'self' ?

**Comment by osifoanosike** [comment]
I thought i needed to make the reverse_sentence a class  method, but I've realized that the user input is actually an instance of the String class, hence I've changed the it to an instance method ( removed the self ).

**Comment by osifoanosike** [comment]
Fixed

**Comment by Shruti2791** [comment]
The exercise is not functioning as expected. 'good morning'.reverse_sentence should return 'morning good'

**Comment by osifoanosike** [comment]
Corrected.

**Comment by Shruti2791** [comment]
Looks good just mind the usage of (!) operator
