### ISSUE TITLE
Ex-15 Primes Upto

### ISSUE THREAD

**Issue by yuktikhurana** [osifoanosike/basicruby#5]
https://github.com/osifoanosike/basicruby/tree/master/15
1. Require prime is written outside the class
2. name of the files in lib should be same as the class name in snakecase. in this case fixnum.rb

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
1. Regex for integer is wrong.Try using(fdgh4567hk)

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
The regex /\d+/ represents a number no doubt.Only thing missing was the meta characters ^ and $.
