### ISSUE TITLE
17 and 19 Sum time

### ISSUE THREAD

**Issue by yuktikhurana** [osifoanosike/basicruby#9]
1. Regex is incorrect.
2. Exception being raised should be rescued
3. raise is spelled incorrectly
4. why require date in main?
5. file name and class name mismatch for lib
   6.Do not hardcode 1 day instead use the value of variable day. https://github.com/osifoanosike/basicruby/blob/master/17/lib/sum_time.rb#L23
6. now here as u can see, every method in the class is a class method. This is an ideal case for using a module as no instantiation required.

**Comment by osifoanosike** [comment]
Fixed

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
1.TIME_REGEX =  /^([0]?\d|1\d|2[0-3]):([0-5]\d):([0-5]\d)$/
[0]\d|1\d can be combined  like [0-1]\d
2. Move require time outside module(ex-17)
3.Also now in main.rb we don't require SumTime.total_time. Simply total_time will work.
4. Add meaningful commit messages. (Like changed module implementation, removed self etc)
5. Also for the exception don't write something went wrong. Let the user know that the time he entered was invalid. Show that message

**Comment by osifoanosike** [comment]
fixed
